{"@t":"2021-01-05T16:16:46.3702100Z","@mt":"【水电费 】 发送了消息：（第三方水电费）","@l":"Debug","SourceContext":"WebAppTest.Hubs.ChatHub","TransportConnectionId":"LJN90or7kNQpNx6peqMVPw","RequestId":"0HM5HIL59U7G9:00000001","RequestPath":"/chatHub","SpanId":"|21d9b064-4f82152f3316b4cc.","TraceId":"21d9b064-4f82152f3316b4cc","ParentId":"","ConnectionId":"0HM5HIL59U7G9"}
{"@t":"2021-01-05T16:18:39.4532845Z","@mt":"【boo】 发送了消息：（hi world\n）","@l":"Debug","SourceContext":"WebAppTest.Hubs.ChatHub","TransportConnectionId":"Q2NP0w4DP3AyTckIGTtakQ","RequestId":"0HM5HIL59U7GB:00000001","RequestPath":"/chatHub","SpanId":"|21d9b067-4f82152f3316b4cc.","TraceId":"21d9b067-4f82152f3316b4cc","ParentId":"","ConnectionId":"0HM5HIL59U7GB"}
{"@t":"2021-01-06T14:48:09.0808158Z","@mt":"Connection id \"{ConnectionId}\", Request id \"{TraceIdentifier}\": An unhandled exception was thrown by the application.","@l":"Error","@x":"System.InvalidOperationException: Headers are read-only, response has already started.\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowHeadersReadOnlyException()\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item(String key, StringValues value)\r\n   at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_ContentType(String value)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)\r\n   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at WebAppTest.Startup.<>c.<<Configure>b__1_0>d.MoveNext() in D:\\workspace\\CSharpProject\\MumuAdmin\\M.Tax\\WebAppTest\\Startup.cs:line 35\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)","ConnectionId":"0HM5IA8AITMJJ","TraceIdentifier":"0HM5IA8AITMJJ:00000001","EventId":{"Id":13,"Name":"ApplicationError"},"SourceContext":"Microsoft.AspNetCore.Server.Kestrel","RequestId":"0HM5IA8AITMJJ:00000001","RequestPath":"/home","SpanId":"|2ddaa2d0-4d6b7358803e1853.","TraceId":"2ddaa2d0-4d6b7358803e1853","ParentId":""}
{"@t":"2021-01-06T14:48:17.4768227Z","@mt":"Connection id \"{ConnectionId}\", Request id \"{TraceIdentifier}\": An unhandled exception was thrown by the application.","@l":"Error","@x":"System.InvalidOperationException: StatusCode cannot be set because the response has already started.\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.set_StatusCode(Int32 value)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode(Int32 value)\r\n   at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_StatusCode(Int32 value)\r\n   at Microsoft.AspNetCore.Builder.ApplicationBuilder.<>c.<Build>b__18_0(HttpContext context)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_2.<Use>b__2()\r\n   at WebAppTest.Startup.<>c.<<Configure>b__1_0>d.MoveNext() in D:\\workspace\\CSharpProject\\MumuAdmin\\M.Tax\\WebAppTest\\Startup.cs:line 35\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)","ConnectionId":"0HM5IA8AITMJK","TraceIdentifier":"0HM5IA8AITMJK:00000001","EventId":{"Id":13,"Name":"ApplicationError"},"SourceContext":"Microsoft.AspNetCore.Server.Kestrel","RequestId":"0HM5IA8AITMJK:00000001","RequestPath":"/","SpanId":"|2ddaa2d1-4d6b7358803e1853.","TraceId":"2ddaa2d1-4d6b7358803e1853","ParentId":""}
{"@t":"2021-01-06T14:55:07.0578959Z","@mt":"Connection id \"{ConnectionId}\", Request id \"{TraceIdentifier}\": An unhandled exception was thrown by the application.","@l":"Error","@x":"System.InvalidOperationException: StatusCode cannot be set because the response has already started.\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.set_StatusCode(Int32 value)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode(Int32 value)\r\n   at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_StatusCode(Int32 value)\r\n   at Microsoft.AspNetCore.Builder.ApplicationBuilder.<>c.<Build>b__18_0(HttpContext context)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_2.<Use>b__2()\r\n   at WebAppTest.Startup.<>c.<<Configure>b__1_0>d.MoveNext() in D:\\workspace\\CSharpProject\\MumuAdmin\\M.Tax\\WebAppTest\\Startup.cs:line 35\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)","ConnectionId":"0HM5IAC783U1L","TraceIdentifier":"0HM5IAC783U1L:00000001","EventId":{"Id":13,"Name":"ApplicationError"},"SourceContext":"Microsoft.AspNetCore.Server.Kestrel","RequestId":"0HM5IAC783U1L:00000001","RequestPath":"/","SpanId":"|116a888e-429699070190dcdc.","TraceId":"116a888e-429699070190dcdc","ParentId":""}
